# Generated by Django 5.1.3 on 2025-05-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramclient',
            name='bot_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
