# Generated by Django 4.2.20 on 2025-05-11 02:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_broadcastmessage_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='buttons_json',
            field=models.TextField(blank=True, null=True, verbose_name='Кнопки (JSON)'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='comment',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='paymentupload',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_payment),
        ),
    ]
