# Generated by Django 4.2.20 on 2025-05-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_broadcastmessage_buttons_json_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaction',
            options={'verbose_name': 'Действие клиента', 'verbose_name_plural': 'Действия клиентов'},
        ),
        migrations.AlterModelOptions(
            name='telegramclient',
            options={'verbose_name': 'Клиент Telegram', 'verbose_name_plural': 'Клиенты Telegram'},
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='broadcasts/', verbose_name='Фото'),
        ),
    ]
