# Generated by Django 5.1.3 on 2025-05-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramclient',
            name='awaiting_support',
            field=models.BooleanField(default=False),
        ),
    ]
