# Generated by Django 4.2.20 on 2025-05-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clientaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='broadcasts/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.broadcastmessage')),
            ],
            options={
                'verbose_name': 'Фото рассылки',
                'verbose_name_plural': 'Фото рассылки',
            },
        ),
    ]
