# Generated by Django 4.2.20 on 2025-05-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_broadcastphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='text_after_media',
            field=models.TextField(blank=True, null=True, verbose_name='Текст после фото (если их много)'),
        ),
    ]
