# Generated by Django 4.2.20 on 2025-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_broadcastmessage_text_after_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramclient',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокировал бота'),
        ),
    ]
