# Generated by Django 5.1.3 on 2025-05-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_broadcastmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.broadcastmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramclient')),
            ],
            options={
                'verbose_name': 'Доставка сообщения',
                'verbose_name_plural': 'Доставки сообщений',
                'unique_together': {('message', 'recipient')},
            },
        ),
    ]
