# Generated by Django 4.2.20 on 2025-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_telegramclient_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaction',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
