# Generated by Django 4.2.20 on 2025-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_clientaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaction',
            name='action',
            field=models.TextField(),
        ),
    ]
