# Generated by Django 4.2.20 on 2025-05-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_clientaction_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to='voice/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.broadcastmessage')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.PositiveSmallIntegerField()),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voice_responses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramclient')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.broadcastmessage')),
            ],
            options={
                'unique_together': {('message', 'client')},
            },
        ),
    ]
