# Generated by Django 4.2.20 on 2025-05-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_broadcastaudio_broadcastvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastaudio',
            name='caption',
            field=models.TextField(blank=True, verbose_name='Текст к аудио'),
        ),
    ]
