# Generated by Django 4.2.20 on 2025-05-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_broadcastaudio_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastaudio',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_mp3/'),
        ),
    ]
