# Generated by Django 4.2.20 on 2025-05-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_broadcastaudio_mp3_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastaudio',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
