# Generated by Django 4.2.20 on 2025-05-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_broadcastaudio_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastaudio',
            name='custom_filename',
            field=models.CharField(blank=True, help_text='Название файла для отправки в Telegram (с расширением .mp3)', max_length=255, null=True),
        ),
    ]
