# Generated by Django 4.2.20 on 2025-06-08 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_broadcastaudio_custom_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="broadcasts/videos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="core.broadcastmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео рассылки",
                "verbose_name_plural": "Видео рассылки",
            },
        ),
    ]
