# Основные состояния
MAIN_MENU, CURRENCY, AMOUNT, METHOD, COMMENT, CONFIRM = range(6)

# Состояния для предложений
(OFFER_STATE_RATE, OFFER_STATE_MIN_MAX, OFFER_STATE_METHODS,
 OFFER_CONFIRM, OFFER_LIST) = range(6, 11)