# Generated by Django 5.1.3 on 2025-05-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='comment',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
